#!/usr/bin/env python3
"""Render portable prompts from the canonical behavior specification. Skill packaging is separate."""
from pathlib import Path
import argparse

ROOT = Path(__file__).resolve().parents[1]

def outputs():
    spec = (ROOT / 'SPEC.md').read_text()
    start, end = '<!-- DUCK_RUNTIME_START -->', '<!-- DUCK_RUNTIME_END -->'
    if spec.count(start) != 1 or spec.count(end) != 1:
        raise ValueError('SPEC.md must contain exactly one runtime projection')
    body = spec.split(start, 1)[1].split(end, 1)[0].strip() + '\n'
    notes = {
        'generic': '',
        'chatgpt': '\n## Host note\nUse available search tools for material current or niche facts; cite retrieved evidence.\n',
        'claude': '\n## Host note\nUse available evidence tools. When unavailable, mark the gap unverified and continue conditionally.\n',
        'coding-agent': '\n## Coding / architecture context\nInspect code, docs, logs, and benchmarks for technical facts. Distinguish measured behavior from architecture judgment. Explore maintenance, coupling, reversibility, and operations when relevant. Duck-mode discussion does not authorize implementation edits.\n',
    }
    result = {ROOT / 'prompts' / f'{name}.md':
              f'# Duck-mode prompt — {name}\n\n<!-- Generated by scripts/build_prompts.py; edit SPEC.md. -->\n\n' + body + note
              for name, note in notes.items()}
    return result

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = []
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        parser.exit(1, 'Out-of-date artifacts: ' + ', '.join(stale) + '\n')
    print('Generated artifacts are current.' if args.check else 'Generated four prompts. Use scripts/build_skill.py to package the skill.')

if __name__ == '__main__':
    main()
