#!/usr/bin/env python3
"""Package the tested generic prompt as a self-contained skill, without modifying prompts."""
import argparse
import hashlib
import io
from pathlib import Path
import zipfile

ROOT = Path(__file__).resolve().parents[1]
PREFIX = ('# Duck-mode prompt — generic\n\n'
          '<!-- Generated by scripts/build_prompts.py; edit SPEC.md. -->\n\n')
FRONTMATTER = '''---
name: duck-mode
description: "Explore ideas and questions through an evolving thought map while preserving the user's ownership of conclusions. Use when the user requests Duck-mode, guided thought exploration, or help thinking without a premature recommendation."
license: MIT
---

<!-- Packaged by scripts/build_skill.py from prompts/generic.md; do not edit this artifact. -->

## Optional examples

Read [references/examples.md](references/examples.md) only when a worked conversation would
help calibrate tone, map semantics, evidence continuation, or reasoning ownership. Do not
load it by default. The behavioral contract below remains authoritative.

'''
METADATA = '''interface:
  display_name: "Duck-mode"
  short_description: "Explore your thoughts without handing over the answer"
  default_prompt: "Use $duck-mode to help me think through: "

policy:
  allow_implicit_invocation: false
'''

def payloads(root=ROOT):
    source = (root / 'prompts/generic.md').read_bytes()
    prefix = PREFIX.encode()
    if not source.startswith(prefix):
        raise ValueError('Unrecognized generic prompt wrapper; refusing to guess the contract boundary')
    # Preserve every byte of the tested contract, including its trailing newline.
    contract = source[len(prefix):]
    if not contract.startswith(b'# Duck-mode behavioral contract\n'):
        raise ValueError('Missing behavioral contract')
    files = {
        'SKILL.md': FRONTMATTER.encode() + contract,
        'agents/openai.yaml': METADATA.encode(),
        'LICENSE': (root / 'LICENSE').read_bytes(),
        'references/examples.md': (root / 'skills/duck-mode/references/examples.md').read_bytes(),
    }
    return files

def archive_bytes(files):
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, 'w', compression=zipfile.ZIP_DEFLATED) as archive:
        for name, content in sorted(files.items()):
            info = zipfile.ZipInfo('duck-mode/' + name, date_time=(2026, 1, 1, 0, 0, 0))
            info.create_system = 3
            info.external_attr = 0o100644 << 16
            info.compress_type = zipfile.ZIP_DEFLATED
            archive.writestr(info, content)
    return buffer.getvalue()

def outputs(root=ROOT):
    files = payloads(root)
    archive = archive_bytes(files)
    folder = root / 'skills/duck-mode'
    archive_name = 'duck-mode.zip'
    result = {folder / name: content for name, content in files.items()}
    result[root / 'dist' / archive_name] = archive
    result[root / 'dist' / (archive_name + '.sha256')] = (
        hashlib.sha256(archive).hexdigest() + '  ' + archive_name + '\n').encode()
    return result

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Verify folder, archive and checksum without writing')
    args = parser.parse_args()
    stale = []
    for path, expected in outputs().items():
        if args.check:
            if not path.exists() or path.read_bytes() != expected:
                stale.append(str(path.relative_to(ROOT)))
        elif not path.exists() or path.read_bytes() != expected:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(expected)
    if stale:
        parser.exit(1, 'Stale package artifacts: ' + ', '.join(stale) + '\n')
    print('Skill folder, archive and checksum are current.' if args.check else
          'Packaged skill folder and archive; generic.md was read only.')

if __name__ == '__main__':
    main()
